### ISSUE TITLE
数据可视化工具

### ISSUE THREAD

**Issue by allenfantasy** [gzhack/2015-gzhack-faq#1]
### Step 1

列举常用（尽量简单易用）的可视化工具及 demo；
### Step 2

撰写可视化工具的使用教程

**Comment by ZedZhang** [comment]
知乎有比较详细的推荐：http://www.zhihu.com/question/19929609

**Comment by allenfantasy** [comment]
@ZedZhang 其实里面大部分都不是很适合，还是只有几个常用的工具是支持各种不同类型的数据图表的。
